baseURL: 'https://frankkirin.github.io/MyPMBlogs/'
languageCode: 'cn'
title: '产品经理之路'
theme: 'hugo-PaperMod'
paginate: 7

params:
    author: Frank Ye
    defaultTheme: auto
    ShowPostNavLinks: true
    ShowBreadCrumbs: true

    editPost:
        URL: "https://frankkirin.github.io/MyPMBlogs/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
    main:
        - identifier: categories
          name: 分类
          url: /categories/
          weight: 10
        - identifier: tags
          name: 标签
          url: /tags/
          weight: 20

pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai
